CREATE TABLE  BloodDonationDB.dbo.PersonArchive(
[PersonID] BIGINT NOT NULL,
[SA_ID_Number] CHAR(13) NULL,
[PassportNumber] BIGINT NULL,
[CountryOfResidence] VARCHAR(50) NOT NULL,
[HIV_Status] BIT NOT NULL DEFAULT 0,
[FirstName] VARCHAR(50) NOT NULL,
[MiddleName] VARCHAR(50) NULL,
[LastName] VARCHAR(50) NOT NULL,
[Title] VARCHAR(6) NOT NULL,
[Sex] CHAR(1) NOT NULL,
[Gender] VARCHAR(50) NOT NULL,
[DoB] DATETIME2 NOT NULL,
[Cellphone] VARCHAR(25) NOT NULL,
[HomeNumber] VARCHAR(25) NOT NULL,
[WorkNumber] VARCHAR(25) NOT NULL,
[Email] VARCHAR(50) NOT NULL,
[AddressComplexName] VARCHAR(50) NULL,
[AddressUnitNumber] SMALLINT NULL,
[AddressStreetName] VARCHAR(50) NOT NULL,
[AddressStreetNumber] SMALLINT NOT NULL,
[AddressSuburb] VARCHAR(50) NOT NULL,
[AddressCity] VARCHAR(50) NOT NULL,
[AddressProvince] VARCHAR(50) NOT NULL,
[AddressCountry] VARCHAR(50) NOT NULL,
[EmergencyContactName] VARCHAR(50) NOT NULL ,
[EmergencyContactSurname] VARCHAR(50) NOT NULL ,
[EmergencyContactRelation] VARCHAR(50) NOT NULL,
[EmergencyContactCellphone] VARCHAR(25) NULL,
[EmergencyContactHomeNumber] VARCHAR(25) NULL,
[EmergencyContactWorkNumber] VARCHAR(25) NULL,
[BloodTypeName] VARCHAR(50) NOT NULL,
[BloodTypeDescription] VARCHAR(100) NULL,
[TimeStamp]  DATETIME2 NOT NULL DEFAULT GETDATE(),
PRIMARY KEY ([PersonID])
);
