CREATE TABLE  BloodDonationDB.dbo.Donor(
[DonorID] BIGINT IDENTITY(1,1) NOT NULL,
[PersonID] BIGINT NOT NULL,
[TestResultID] BIGINT NOT NULL,
[TimeStamp] DATETIME2 NOT NULL DEFAULT GETDATE(),
PRIMARY KEY ([DonorID])
)