--OrderPlaced Table
ALTER TABLE [OrderPlaced]
ADD
FOREIGN KEY ([FacilityID]) REFERENCES Facility([FacilityID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [OrderPlaced]
ADD
FOREIGN KEY ([OrderStatusID]) REFERENCES OrderStatus([OrderStatusID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [OrderPlaced]
ADD
FOREIGN KEY ([ShipmentID]) REFERENCES Shipment([ShipmentID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

--OrderItem Table
ALTER TABLE [OrderItem]
ADD
FOREIGN KEY ([OrderID]) REFERENCES OrderPlaced([OrderID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [OrderItem]
ADD
FOREIGN KEY ([InventoryID]) REFERENCES Inventory([InventoryID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
