CREATE TABLE BloodDonationDB.dbo.Staff(
[StaffID] BIGINT IDENTITY(1,1) NOT NULL,
[PersonID] BIGINT NOT NULL,
[DateEmployed] DATETIME2 NOT NULL,
[LastDayOfEmployment] DATETIME2 NULL,
[JobTitle] VARCHAR(25) NOT NULL,
[DonationBranchID] BIGINT NOT NULL,
[TimeStamp] DATETIME2 NOT NULL DEFAULT GETDATE(),
PRIMARY KEY ([StaffID])
);