CREATE TABLE BloodDonationDB.dbo.Inventory(
[InventoryID] BIGINT IDENTITY(1,1) NOT NULL,
[BloodTypeID] BIGINT NOT NULL,
[DonorID] BIGINT NOT NULL,
[RecipientID] BIGINT NOT NULL,
[IsStockUsable] BIT NOT NULL, 
[PassedAllTests] BIT NOT NULL,
[StatusID] SMALLINT NOT NULL,
[DestroyedDate] DATETIME2, 
[DonationBranchID] BIGINT NOT NULL,
[StorageFacilityID] BIGINT NOT NULL,
[ItemTypeID] SMALLINT NOT NULL,
[DonationDate] DATETIME2 NOT NULL,
[ExpiryDate] DATETIME2 NOT NULL,
[TimeStamp] DATETIME2 NOT NULL DEFAULT GETDATE(),
PRIMARY KEY ([InventoryID])
);