CREATE TABLE  BloodDonationDB.dbo.Person(
[PersonID] BIGINT IDENTITY(1,1) NOT NULL,
[SA_ID_Number] CHAR(13) NULL,
[PassportNumber] BIGINT NULL,
[CountryOfResidence] VARCHAR(50) NOT NULL,
[HIV_Status] BIT NOT NULL DEFAULT 0,
[FirstName] VARCHAR(50) NOT NULL,
[MiddleName] VARCHAR(50) NULL,
[LastName] VARCHAR(50) NOT NULL,
[Title] VARCHAR(6) NOT NULL,
[Sex] CHAR(1) NOT NULL,
[Gender] VARCHAR(50) NOT NULL,
[DoB] DATE NOT NULL,
[TelephoneID] BIGINT NOT NULL,
[EmailID] BIGINT NOT NULL,
[AddressID] BIGINT NOT NULL,
[EmergencyContactID] BIGINT NOT NULL,
[BloodTypeID] SMALLINT NOT NULL,
[TimeStamp]  DATETIME2 NOT NULL DEFAULT GETDATE(),
PRIMARY KEY ([PersonID])
);
GO
