ALTER TABLE
    [Facility]
ADD
    CONSTRAINT FK_Facility_FacilityType FOREIGN KEY ([FacilityTypeID]) REFERENCES FacilityType([FacilityTypeID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    [Facility]
ADD
    CONSTRAINT FK_Facility_Address FOREIGN KEY ([AddressID]) REFERENCES Address([AddressID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    [Facility]
ADD
    CONSTRAINT FK_Facility_Telephone FOREIGN KEY ([TelephoneID]) REFERENCES Telephone([TelephoneID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    [Facility]
ADD
    CONSTRAINT FK_Facility_Email FOREIGN KEY ([EmailID]) REFERENCES Email([EmailID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    [Facility]
ADD
    CONSTRAINT FK_Facility_EmergencyContact FOREIGN KEY ([EmergencyContactID]) REFERENCES EmergencyContact([EmergencyContactID]) ON DELETE NO ACTION ON UPDATE NO ACTION;